---
openapi: "3.0.0"
info:
  version: 0.0.0
  title: ReportingSystem
  description: API for ReportingSystem Endpoints
servers:
  - url: http://localhost:10001/v0
paths:
  /report:
    get:
      tags:
        - Get WCFB report
      description: Gets a csv report for the WCFB between a start and end date.
      x-eov-operation-handler: endpoints
      operationId: getWCFBReport
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: Start date for report  information
          required: true
        - in: query
          name: endDate
          schema:
            type: string
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: End date for report information
          required: true
      responses:
        "200":
          description: OK
          content:
            text/csv: {}